name: EasyEnvironment
components:
  relation:
    plugin:
      EasyRelationPlugin:
        relations: 'agents_relation'
  space:
    plugin:
      EasySpacePlugin:
        agents: 'map_agents'
  science:
    plugin:
      CausalWorldPlugin:
        num_vars: 8
        target: "Y"
        seed: 42
        budget: 10
        lambda_cost: 0.3
        hint_accuracy: 0.7
        view_ratio: 0.35
        cards_per_edge: 3
        template_mode: "random"
